package fr.smile.training.faq.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fr.smile.training.faq.model.Faq;
import fr.smile.training.faq.service.FaqLocalServiceUtil;

/**
 * The extended model base implementation for the Faq service. Represents a row in the &quot;Faq&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaqImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see FaqImpl
 * @see fr.smile.training.faq.model.Faq
 * @generated
 */
public abstract class FaqBaseImpl extends FaqModelImpl implements Faq {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a faq model instance should use the {@link Faq} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FaqLocalServiceUtil.addFaq(this);
        } else {
            FaqLocalServiceUtil.updateFaq(this);
        }
    }
}
