package fr.smile.training.faq.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import fr.smile.training.faq.model.Faq;
import fr.smile.training.faq.service.FaqService;
import fr.smile.training.faq.service.persistence.FaqPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the faq remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link fr.smile.training.faq.service.impl.FaqServiceImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see fr.smile.training.faq.service.impl.FaqServiceImpl
 * @see fr.smile.training.faq.service.FaqServiceUtil
 * @generated
 */
public abstract class FaqServiceBaseImpl extends BaseServiceImpl
    implements FaqService, IdentifiableBean {
    @BeanReference(type = fr.smile.training.faq.service.FaqLocalService.class)
    protected fr.smile.training.faq.service.FaqLocalService faqLocalService;
    @BeanReference(type = fr.smile.training.faq.service.FaqService.class)
    protected fr.smile.training.faq.service.FaqService faqService;
    @BeanReference(type = FaqPersistence.class)
    protected FaqPersistence faqPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private FaqServiceClpInvoker _clpInvoker = new FaqServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link fr.smile.training.faq.service.FaqServiceUtil} to access the faq remote service.
     */

    /**
     * Returns the faq local service.
     *
     * @return the faq local service
     */
    public fr.smile.training.faq.service.FaqLocalService getFaqLocalService() {
        return faqLocalService;
    }

    /**
     * Sets the faq local service.
     *
     * @param faqLocalService the faq local service
     */
    public void setFaqLocalService(
        fr.smile.training.faq.service.FaqLocalService faqLocalService) {
        this.faqLocalService = faqLocalService;
    }

    /**
     * Returns the faq remote service.
     *
     * @return the faq remote service
     */
    public fr.smile.training.faq.service.FaqService getFaqService() {
        return faqService;
    }

    /**
     * Sets the faq remote service.
     *
     * @param faqService the faq remote service
     */
    public void setFaqService(
        fr.smile.training.faq.service.FaqService faqService) {
        this.faqService = faqService;
    }

    /**
     * Returns the faq persistence.
     *
     * @return the faq persistence
     */
    public FaqPersistence getFaqPersistence() {
        return faqPersistence;
    }

    /**
     * Sets the faq persistence.
     *
     * @param faqPersistence the faq persistence
     */
    public void setFaqPersistence(FaqPersistence faqPersistence) {
        this.faqPersistence = faqPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Faq.class;
    }

    protected String getModelClassName() {
        return Faq.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = faqPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
